database:
  dialect: postgres
  host:  ec2-52-215-68-14.eu-west-1.compute.amazonaws.com
  port: 5432
  dbname: d2d2vtls3cu2p7
  username: tfhrpkthrwnhry
  password: d4f1a4d0125f96696995bc42633cde8cca2aaa4b37f99826cb88e9755fba2ff0
  migration: true

extension:
  master_generator: true
  cors_enabled: true
  security_enabled: true

log:
  format: ${time_rfc3339} [${level}] ${remote_ip} ${method} ${uri} ${status}
  level: 1
  file_path: 

security:
  exclude_path:
    - /api/account/login$
    - /api/account/logout$
    - /api/health$
  user_path:
    - /api/account/.*
  admin_path:
    - /api/.*